FROM nginx:alpine

# Copy static frontend files
COPY . /usr/share/nginx/html

# Copy entrypoint script and make it executable
COPY ./frontend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

CMD ["/entrypoint.sh"]
